### ISSUE TITLE
FR - Adding Footnote Section  

### ISSUE THREAD

**Issue by Friedolito** [MichaBrugger/obsidian-footnotes#13]
Thank your developing this plugin!

I have from time to time the problem, that footnotes get mingled in to the note. 
Something that I do, is to  manually add a level 1 heading above the footnotes, so they heave a dedicated section. 
Maybe this is a small feature to incorporate into the plugin ? 
When adding the first footnote, a heading is added right above, with a name of your choosing.

**Comment by Comprehensive-Jason** [comment]
Suggestion noted.

The issue is that lots of people (including me) have templates with preset headings at the end of the file for footnotes to slot in already, and would like to keep control over that heading in the template, and not in the plugin.

The plugin adds footnotes to the end of the document. A quick way to create the separation without much effort is just to hit the <kbd>enter</kbd> key a couple times before starting to type at the top of a note, that way there are a couple of blank lines between the end of your writing and the start of the footnotes. Is that a good solution, or would you still like the option to add a footnote section heading?

**Comment by Friedolito** [comment]
That is great to hear and thank you for the workaround! 
It's nothing essential, but would be a nice QOL improvement :)

**Comment by Comprehensive-Jason** [comment]
completed in 7b3ec16

**Comment by Friedolito** [comment]
Thank you!!
