### ISSUE TITLE
Math notations not displayed properly in table of contents

### ISSUE THREAD

**Issue by The-Alley** [MichaBrugger/obsidian-footnotes#33]
Hello,

When there are math notations in headings, they are not displayed properly in the table of contents (ToC).
For example, the following heading
<img width="191" alt="image" src="https://github.com/MichaBrugger/obsidian-footnotes/assets/98622858/91ebf2ee-e0b0-4e9d-9e6b-34d1e3cee3f5">
 is displayed like this
<img width="214" alt="image" src="https://github.com/MichaBrugger/obsidian-footnotes/assets/98622858/ae9925c3-e374-4292-bf55-0e766e37822a">
 in the ToC in both reading and source mode.
 I am not sure if this is the intended behaviour. 
Thanks in advance.

**Comment by Comprehensive-Jason** [comment]
Sir, this is a plugin for footnotes. It doesn't do anything to the headings. 
Is your 2nd image a link to the heading shown in the first image? If so, this is normal behavior.

Here's it in source mode: 
![image](https://github.com/MichaBrugger/obsidian-footnotes/assets/68677082/0caf5082-a8ba-4fef-9da8-8228ef9aaccc)

Here's it in reading mode:
![image](https://github.com/MichaBrugger/obsidian-footnotes/assets/68677082/9258e41d-c13f-417b-99e6-ac230e60ba2a)

As you can see, LaTeX doesn't work inside links to headings. This is because the internal linking gets messed up by the LaTeX logic, so the Obsidian team just disables LaTeX inside internal links.
